### PR TITLE
Convert codebase to use CustomTkinter

### PR DESCRIPTION
**Pull request by dishb**
Implements #29

### CODE REVIEW

**Comment by jacobranz** [comment]
Thank you for your work! Looking now.

**Comment by jacobranz** [comment]
Initial tests failing, there are still unresolved issues with frame resolution. Main.py is unable to initialize the page container needed in order to swap between views. This may need an architectural rework. After about an hour of troubleshooting I was unable to get it to work as is. 

- Error: `TypeError: PageContainer.__init__() takes 1 positional argument but 2 were given`

**Comment by jacobranz** [comment]
Currently experiencing issues with frame initialization. Appears as if the super class is still referencing regular tkinter libraries and not using customtkinter. Will continue digging on this tomorrow. This error occurs when attempting run any frame on line 33 of main.py.

- Error: `super().__init__(self, parent, controller)`

**Comment by dishb** [comment]
I would try to find and fix the bug, but I am unable to run the project due to my lack of knowledge on MySQL and databases. I did try setting up the database, but it didn't work. 😅

**Comment by jacobranz** [comment]
Of course! I have uploaded a sql script (to the SQL folder of the project) that will generate the db after you create the schema. I would recommend installing mysql workbench. It is the easiest way to graphically engage with the database. Let me know if you have any issues, I walk through the steps in the comments located in the script!

**Comment by dishb** [comment]
Thanks! The SQL script and your instructions were super useful, I got it working! I'm looking at the bug right now, at it looks like you're setting the master of the `Example` and `Math150` (and other) classes as themselves.

**Comment by jacobranz** [comment]
Glad to hear! I will also be looking for at this later tonight!

**Comment by dishb** [comment]
> Glad to hear! I will also be looking for at this later tonight!

@jacobranz - I've fixed the issue, it wasn't a CTk issue but rather an issue in `main.py` with the "master" widget that was being passed to the `Example`, `Math150`, etc. classes. I removed an extra argument and used a keyword argument to make sure the correct widget was passed as the master. 

You can look at the final output to make sure everything works.

There are a few warnings about unoptimized images, but nothing breaking/crashing the app. I can fix those after this PR is merged.

**Comment by jacobranz** [comment]
Thank you! Great work. It works, there are just display issues within the manage student and teacher frames. Those are now resolved with the latest push as well. You can check the commit history if interested.

Also, in testing the actual database I dropped the schema and rebuilt with that script I gave you. However when attempting to create an entry there were errors with the primary key integers. You will need to delete your current schema and regenerate with the newest version of my sql script. It has extra "not null auto_increment" values attached to all the primary keys.

**Comment by dishb** [comment]
I'll take a look at those issues this weekend. I've updated my fork's `main` branch, thank you!

**Pull request merged**
